export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const PUB_SUB = 'PUB_SUB';
export const NEW_PENDING_ORDER = 'NEW_PENDING_ORDER';
export const NEW_COOKED_ORDER = 'NEW_COOKED_ORDER';
export const NEW_ORDER_UPDATE = 'NEW_ORDER_UPDATE';

export const RESULT_CODE = {
  SUCCESS: 10000,
  FAILE: 10001,
  VALID_EMAIL: 20001,
  VALID_USERNAME: 20002,
};
